M48
; DRILL file {KiCad (6.0.5-0)} date Tuesday 23 May 2023 at 22:47:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-23T22:47:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.100
%
G90
G05
T1
X106.225Y-62.35
X106.225Y-71.1
T2
X52.53Y-69.075
X52.53Y-73.925
T3
X49.5Y-68.775
X49.5Y-74.225
T4
X50.0Y-50.0
X105.0Y-50.0
X105.0Y-95.0
T0
M30
